### ISSUE TITLE
Reason for dividing the secret key by 8 (the cofactor)

### ISSUE THREAD

**Issue by TheHawkis** [david-oswald/jc_curve25519#1]
Can’t help to notice that the secrete key are shifted by 3 and later on the public key are doubled by 8. This actions cancel each outer out.  Why is this done?
Are there any security reasons for this or some legacy in the interface in the over the air interface?

**Comment by david-oswald** [comment]
*tl,dr:* this is done to make things work with the way Javacard (or the card I used) handles elliptic curves.

I had to pass the group order r = 2^252 + 27742317777372353535851937790883648493 here: https://github.com/david-oswald/jc_curve25519/blob/master/src/curve25519/Curve25519Test.java#L184. The card I had did not allow me to pass a scalar (here the secret key) larger than the group order.

But in Curve25519 the secret key is clamped in a certain way (note that the 3 LSBits are always zero) and by design always > 2^254, which would not be accepted by the card. So to address this issue, we compute the public key as PK' = (sk >> 3) * P instead of PK = sk * P. 

Then, to avoid the need to implement BigInt arithmetic and further doubling on the card, we simply add the three trailing zero bits on the side of the host, i.e. compute PK = 8 * PK' to make it a standard Curve25519 key again.

**Comment by TheHawkis** [comment]
Thanks for quick and great response!
Just a small question. Another approach would have been to run modulus on the secret key with the group order before running the scalar multiplication. Was this approach considered?  In both approaches the protection against small order attacks is lost from the cards perspective. If the card and the PC sides is considered one unit I guess the small order attack protection still is intact with the shift approach. Feels like I am missing something.

Some example code used with https://ed25519.cr.yp.to/python/ed25519.py. **Sorry for using Ed25519 but it should work in the same way**:
```
import binascii
import ed25519

def bytesFromHex(hex):
  temp = binascii.unhexlify(hex)
  return sum(2**i * ed25519.bit(temp,i) for i in range(0,ed25519.b))

def hexFromBytes(bytes):
  bits = [(bytes >> i) & 1 for i in range(ed25519.b)]
  temp = ''.join([chr(sum([bits[i * 8 + j] << j for j in range(8)])) for i in range(ed25519.b/8)])
  return binascii.hexlify(temp)

# a is already clamped
a = bytesFromHex("f89640cda9a4fd82f6e456121d2376fb54c7102da01ed9f3d40f777d047a1d6a")
A = bytesFromHex("3a5027279bad33ac129a72939d3cfac880732bf7a1d85ee0d6c431a3bd13100b")

print("Ref:   "+hexFromBytes(A))
print("Org:   "+hexFromBytes(ed25519.scalarmult(ed25519.B, a)[1]))

trim = a % ed25519.l
print("Mod l: "+hexFromBytes(ed25519.scalarmult(ed25519.B, trim)[1]))

shifted = a >> 3
m1 = ed25519.scalarmult(ed25519.B, shifted)
m2 = ed25519.edwards(m1, m1)
m4 = ed25519.edwards(m2, m2)
m8 = ed25519.edwards(m4, m4)
print("Shift: "+hexFromBytes(m8[1]))

# Print
#Ref:   3a5027279bad33ac129a72939d3cfac880732bf7a1d85ee0d6c431a3bd13100b
#Org:   3a5027279bad33ac129a72939d3cfac880732bf7a1d85ee0d6c431a3bd13100b
#Mod l: 3a5027279bad33ac129a72939d3cfac880732bf7a1d85ee0d6c431a3bd13100b
#Shift: 3a5027279bad33ac129a72939d3cfac880732bf7a1d85ee0d6c431a3bd13100b
```

**Comment by david-oswald** [comment]
The problem with running the modulus on the card side is that you'd have to implement some long-number arithmetic on the card, which I tried to avoid for several reasons (mainly speed and also security to some extent). 

Regarding the small order protection: I'm not sure to which extent this causes a problem, but the only difference is that instead of computing K = sk * A (assuming A is the public key of the other party input to the DH) we compute K' = (sk >> 3) * A, discarding three null bits.

**Comment by TheHawkis** [comment]
Ok! Thanks.
Great repo!
